wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1694012047.203065
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 512
dropout:
  desc: null
  value: 0
epochs:
  desc: null
  value: 800
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0004
temp:
  desc: null
  value: 1
weight_angle:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 0
weight_pix:
  desc: null
  value: 0.01
